[target.loongarch64-unknown-none]
rustflags = [
    "-Clink-arg=-Tsrc/linker.ld",
    "-Cforce-frame-pointers=yes",
    "-Clink-arg=-nostdlib",
    "-Clink-arg=-static",
    "-Cforce-frame-pointers=yes",
]
linker = "loongarch64-linux-gnu-gcc"

[target.riscv64gc-unknown-none-elf]
rustflags = ["-Clink-args=-Tsrc/linker-rv.ld"]

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"